// docker-compose.yml
version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    # 8.x
    environment:
		-discovery.type=single-node
    ports:
      - 9200:9200  
    ulimits:
      memlock:
        soft: -1
        hard: -1   
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana   
    ports:
      - 5601:5601 